# Generated by Django 6.0 on 2026-01-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
