# Generated by Django 6.0 on 2026-01-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewanswer_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='number_of_questions',
            field=models.IntegerField(default=5),
        ),
    ]
