# Generated by Django 6.0 on 2026-01-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_interview_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
